import { Dimensions, Platform, StyleSheet } from 'react-native';
const { width } = Dimensions.get('window');
const SIDEBAR_WIDTH = 280;
export const styles = StyleSheet.create({
    container: { flex: 1, flexDirection: "row", backgroundColor: "#f5f7fa" },
    sidebar: { width: SIDEBAR_WIDTH, backgroundColor: "#1e1e2e", paddingTop: Platform.OS === "ios" ? 60 : 40 },
    sidebarHeader: { padding: 24, alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#333" },
    logoContainer: { width: 70, height: 70, backgroundColor: "#4a00e0", borderRadius: 20, justifyContent: "center", alignItems: "center", marginBottom: 12 },
    logoText: { fontWeight: "bold", fontSize: 28, color: "#fff" },
    sidebarTitle: { fontSize: 18, color: "#aaa", fontWeight: "600" },
    menuItem: { flexDirection: "row", alignItems: "center", paddingVertical: 16, paddingHorizontal: 24, gap: 16 },
    menuItemActive: { backgroundColor: "#4a00e0", borderLeftWidth: 4, borderLeftColor: "#00d4ff" },
    menuText: { fontSize: 16, color: "#a0a0a0" },
    menuTextActive: { color: "#fff", fontWeight: "600" },
    logoutMenuItem: { flexDirection: "row", alignItems: "center", paddingVertical: 18, paddingHorizontal: 24, gap: 16, borderTopWidth: 1, borderTopColor: "#333" },
    logoutMenuText: { color: "#ff6b6b", fontSize: 16, fontWeight: "600" },
    roleTeacher: { backgroundColor: "#e91e63", color: "#fff" },
    roleStudent: { backgroundColor: "#00bcd4", color: "#fff" },
    mainContent: { flex: 1 },
    // Trong file styles của admin (index.styles.ts hoặc sidebar.styles.ts)

    dashboardMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderTopWidth: 1,
        borderTopColor: '#334155',
    },

    dashboardMenuText: {
        color: '#4ade80',
        fontSize: 15,
        fontWeight: '600',
        marginLeft: 12,
    },
    header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 24, backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: "#eee" },
    pageTitle: { fontSize: 28, fontWeight: "bold", color: "#1a1a2e" },
    headerActions: { flexDirection: "row", alignItems: "center", gap: 16 },
    searchInput: { width: 320, backgroundColor: "#f1f3f5", padding: 14, borderRadius: 16, fontSize: 16 },
    addBtn: { backgroundColor: "#4a00e0", flexDirection: "row", alignItems: "center", paddingHorizontal: 20, paddingVertical: 14, borderRadius: 16, gap: 8 },
    addBtnText: { color: "#fff", fontWeight: "600" },
    content: { flex: 1, padding: 24 },
    statCard: {
        backgroundColor: "#fff",
        padding: 24,
        borderRadius: 20,
        alignItems: "center",
        width: (width - 80) / 3,
        elevation: 8,
        shadowColor: "#000",
        shadowOpacity: 0.15,
        shadowRadius: 10,
    },
    statNumber: { fontSize: 32, fontWeight: "bold", color: "#1a1a2e", marginVertical: 8 },
    statLabel: { fontSize: 16, color: "#666" },
    chartContainer: { alignItems: "center", backgroundColor: "#1e1e2e", padding: 16, borderRadius: 20 },
    chartTitle: { fontSize: 20, fontWeight: "bold", color: "#fff", marginBottom: 16 },
    notifBtn: { backgroundColor: "#4a00e0", padding: 14, borderRadius: 50, position: "relative" },
    notifBadge: { position: "absolute", top: 8, right: 8, backgroundColor: "#e91e63", borderRadius: 10, width: 18, height: 18, justifyContent: "center", alignItems: "center" },
    table: { backgroundColor: "#fff", borderRadius: 20, overflow: "hidden", elevation: 8, shadowColor: "#000", shadowOpacity: 0.15, shadowRadius: 20, marginBottom: 32 },
    tableHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, backgroundColor: "#4a00e0" },
    tableTitle: { fontSize: 20, fontWeight: "bold", color: "#fff" },
    itemCount: { fontSize: 14, color: "#e0d0ff" },
    row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderBottomWidth: 1, borderBottomColor: "#f0f0f0" },
    rowContent: { flexDirection: "row", alignItems: "center", gap: 20, flex: 1 },
    mainText: { fontSize: 17, fontWeight: "600", color: "#1a1a2e" },
    rowDetails: { flex: 1 },
    detailText: { fontSize: 14, color: "#666", marginBottom: 4 },
    badgeContainer: { marginLeft: 12 },
    badgePublic: {
        backgroundColor: "#e8f5e8", color: "#2e7d32", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, fontSize:
            12
    },
    badgePrivate: { backgroundColor: "#ffebee", color: "#c62828", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, fontSize: 12 },
    roleBadge: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, fontSize: 12, fontWeight: "bold", backgroundColor: "#e0e0e0" },
    roleAdmin: { backgroundColor: "#4a00e0", color: "#fff" },
    actions: { flexDirection: "row", gap: 16 },
    editBtn: { padding: 8 },
    deleteBtn: { padding: 8 },
    comingSoonText: { textAlign: "center", fontSize: 24, color: "#999", marginTop: 100 },
    modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "center", alignItems: "center" },
    modalContent: { width: "90%", maxWidth: 500, backgroundColor: "#fff", borderRadius: 20, padding: 28 },
    modalTitle: { fontSize: 22, fontWeight: "bold", marginBottom: 24, textAlign: "center", color: "#1a1a2e" },
    input: { backgroundColor: "#f1f3f5", padding: 16, borderRadius: 12, marginBottom: 16, fontSize: 16 },
    modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 16, marginTop: 10 },
    cancelBtn: { paddingHorizontal: 20, paddingVertical: 10 },
    cancelText: { color: "#666", fontSize: 16 },
    saveBtn: { backgroundColor: "#4a00e0", paddingHorizontal: 28, paddingVertical: 12, borderRadius: 12 },
    saveText: { color: "#fff", fontWeight: "600", alignSelf: "center", fontSize: 16 },
    chapterModalContainer: {
        width: "95%",
        height: "90%", // Chiếm 90% chiều cao màn hình, không bao giờ tràn
        maxWidth: 700,
        backgroundColor: "#fff",
        borderRadius: 20,
        overflow: "hidden",
        elevation: 10,
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 20,
    },
    chapterModalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#4a00e0",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    chapterModalTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#fff",
    },
    chapterModalFooter: {
        flexDirection: "row",
        justifyContent: "flex-end",
        padding: 20,
        backgroundColor: "#f8f9fa",
        borderTopWidth: 1,
        borderTopColor: "#eee",
        gap: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        marginBottom: 10,
        marginTop: 10,
    },
    bookSelectorContainer: {
        marginBottom: 20,
        paddingVertical: 8,
        backgroundColor: "#f5f5f5",
        borderRadius: 12,
    },
    bookTag: {
        paddingHorizontal: 18,
        paddingVertical: 14,
        backgroundColor: "#fff",
        borderRadius: 12,
        marginRight: 12,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    bookTagSelected: {
        backgroundColor: "#4a00e0",
        borderColor: "#4a00e0",
    },
    bookTagText: {
        fontWeight: "600",
        color: "#333",
    },
    bookTagTextSelected: {
        color: "#fff",
    },
    emptyText: {
        color: "#999",
        fontStyle: "italic",
        padding: 16,
    },
    segmentCard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        elevation: 3,
        shadowColor: "#000",
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    segmentHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    segmentIndex: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#4a00e0",
    },
    segmentInput: {
        marginBottom: 12,
    },
    addSegmentBtn: {
        flexDirection: "row",
        backgroundColor: "#4CAF50",
        padding: 16,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
    },
    addSegmentText: {
        color: "#fff",
        fontWeight: "600",
        fontSize: 16,
    },
})