/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/list` | `/books/list`; params?: Router.UnknownInputParams; } | { pathname: `/api/jishoApi`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/[bookId]/[chapterId]` | `/books/[bookId]/[chapterId]`, params: Router.UnknownInputParams & { bookId: string | number;chapterId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/list` | `/books/list`; params?: Router.UnknownOutputParams; } | { pathname: `/api/jishoApi`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/[bookId]/[chapterId]` | `/books/[bookId]/[chapterId]`, params: Router.UnknownOutputParams & { bookId: string;chapterId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/layout${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/books/list${`?${string}` | `#${string}` | ''}` | `/books/list${`?${string}` | `#${string}` | ''}` | `/api/jishoApi${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/layout` | `/layout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/list` | `/books/list`; params?: Router.UnknownInputParams; } | { pathname: `/api/jishoApi`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(tabs)'}/books/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/books/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(auth)'}${'/(tabs)'}/books/[bookId]/[chapterId]` | `/books/[bookId]/[chapterId]`, params: Router.UnknownInputParams & { bookId: string | number;chapterId: string | number; } };
    }
  }
}
